%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-rqt-moveit
Version:        0.5.9
Release:        2%{?dist}%{?release_suffix}
Summary:        ROS rqt_moveit package

License:        BSD
URL:            http://wiki.ros.org/rqt_moveit
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-python-qt-binding >= 0.2.19
Requires:       ros-noetic-rosnode
Requires:       ros-noetic-rospy
Requires:       ros-noetic-rostopic
Requires:       ros-noetic-rqt-gui
Requires:       ros-noetic-rqt-gui-py
Requires:       ros-noetic-rqt-py-common
Requires:       ros-noetic-rqt-topic
Requires:       ros-noetic-sensor-msgs
BuildRequires:  python3-setuptools
BuildRequires:  ros-noetic-catkin
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
An rqt-based tool that assists monitoring tasks for MoveIt! motion planner
developers and users. Currently the following items are monitored if they are
either running, existing or published: Node: /move_group Parameter:
[/robot_description, /robot_description_semantic] Topic: Following types are
monitored. Published &quot;names&quot; are ignored. [sensor_msgs/PointCloud,
sensor_msgs/PointCloud2, sensor_msgs/Image, sensor_msgs/CameraInfo] Since this
package is not made by the MoveIt! development team (although with assistance
from the them), please post issue reports to the designated tracker (not
MoveIt!'s main tracker).

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Tue Jun 02 2020 Isaac I.Y. Saito <iisaito@kinugarage.com> - 0.5.9-2
- Autogenerated by Bloom

* Tue Jun 02 2020 Isaac I.Y. Saito <iisaito@kinugarage.com> - 0.5.9-1
- Autogenerated by Bloom

* Sun Apr 19 2020 Isaac I.Y. Saito <iisaito@kinugarage.com> - 0.5.8-1
- Autogenerated by Bloom

