Name:           ros-melodic-rqt-moveit
Version:        0.5.7
Release:        0%{?dist}
Summary:        ROS rqt_moveit package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/rqt_moveit
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-python-qt-binding >= 0.2.19
Requires:       ros-melodic-rosnode
Requires:       ros-melodic-rospy
Requires:       ros-melodic-rostopic
Requires:       ros-melodic-rqt-gui
Requires:       ros-melodic-rqt-gui-py
Requires:       ros-melodic-rqt-py-common
Requires:       ros-melodic-rqt-topic
Requires:       ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-catkin

%description
An rqt-based tool that assists monitoring tasks for MoveIt! motion planner
developers and users. Currently the following items are monitored if they are
either running, existing or published: Node: /move_group Parameter:
[/robot_description, /robot_description_semantic] Topic: Following types are
monitored. Published &quot;names&quot; are ignored. [sensor_msgs/PointCloud,
sensor_msgs/PointCloud2, sensor_msgs/Image, sensor_msgs/CameraInfo] Since this
package is not made by the MoveIt! development team (although with assistance
from the them), please post issue reports to the designated tracker (not
MoveIt!'s main tracker).

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Apr 12 2018 Isaac I.Y. Saito <iisaito@kinugarage.com> - 0.5.7-0
- Autogenerated by Bloom

